/*
 * Guardian Express
 * <p>Guardian Express, Fraud Score estima la probabilidad de fraude de originación en el momento de otorgamiento del crédito, representada en un puntaje de 0 a 1, donde un valor más alto indica un mayor riesgo de fraude. El formato express da apertura a que pueda ser consumido sin necesidad de un Rerporte de Crédito..<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.GuardianExpressSimulacion.client.model;

import com.google.gson.annotations.SerializedName;


import java.math.BigDecimal;
import java.util.Objects;
/**
 * RequestDatosGenerales
 */


public class RequestDatosGenerales {
  @SerializedName("folioOtorgante")
  private String folioOtorgante = null;

  @SerializedName("persona")
  private RequestDatosGeneralesPersona persona = null;

  public RequestDatosGenerales folioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
    return this;
  }

   /**
   * Get folioOtorgante
   * @return folioOtorgante
  **/
  public String getFolioOtorgante() {
    return folioOtorgante;
  }

  public void setFolioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
  }

  public RequestDatosGenerales persona(RequestDatosGeneralesPersona persona) {
    this.persona = persona;
    return this;
  }

   /**
   * Get persona
   * @return persona
  **/
  public RequestDatosGeneralesPersona getPersona() {
    return persona;
  }

  public void setPersona(RequestDatosGeneralesPersona persona) {
    this.persona = persona;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDatosGenerales requestDatosGenerales = (RequestDatosGenerales) o;
    return Objects.equals(this.folioOtorgante, requestDatosGenerales.folioOtorgante) &&
        Objects.equals(this.persona, requestDatosGenerales.persona);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folioOtorgante, persona);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDatosGenerales {\n");
    
    sb.append("    folioOtorgante: ").append(toIndentedString(folioOtorgante)).append("\n");
    sb.append("    persona: ").append(toIndentedString(persona)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
