/*
 * Guardian Express
 * <p>Guardian Express, Fraud Score estima la probabilidad de fraude de originación en el momento de otorgamiento del crédito, representada en un puntaje de 0 a 1, donde un valor más alto indica un mayor riesgo de fraude. El formato express da apertura a que pueda ser consumido sin necesidad de un Rerporte de Crédito..<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.GuardianExpressSimulacion.client.model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * RequestDatosGeneralesPersonaDomicilio
 */


public class RequestDatosGeneralesPersonaDomicilio {
  @SerializedName("direccion")
  private String direccion = null;

  @SerializedName("colonia")
  private String colonia = null;

  @SerializedName("delegacionMunicipio")
  private String delegacionMunicipio = null;

  @SerializedName("ciudad")
  private String ciudad = null;

  @SerializedName("estado")
  private CatalogoEstados estado = null;

  @SerializedName("cp")
  private String cp = null;

  public RequestDatosGeneralesPersonaDomicilio direccion(String direccion) {
    this.direccion = direccion;
    return this;
  }

   /**
   * Reportar el nombre de la calle, número exterior, número interior. Deben considerarse avenida,cerrada, manzana, lote, edificio,departamento etc. Debe contener por lo menos dos cadenas de caracteres para que el registro sea válido, de lo contrario el registro será rechazado.
   * @return direccion
  **/
  public String getDireccion() {
    return direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public RequestDatosGeneralesPersonaDomicilio colonia(String colonia) {
    this.colonia = colonia;
    return this;
  }

   /**
   * Reportar la colonia a la cual pertenece la dirección contenida en el elemento dirección.
   * @return colonia
  **/
  public String getColonia() {
    return colonia;
  }

  public void setColonia(String colonia) {
    this.colonia = colonia;
  }

  public RequestDatosGeneralesPersonaDomicilio delegacionMunicipio(String delegacionMunicipio) {
    this.delegacionMunicipio = delegacionMunicipio;
    return this;
  }

   /**
   * Reportar la delegación o municipio a la cual pertenece la dirección contenida en el elemento Dirección.
   * @return delegacionMunicipio
  **/
  public String getDelegacionMunicipio() {
    return delegacionMunicipio;
  }

  public void setDelegacionMunicipio(String delegacionMunicipio) {
    this.delegacionMunicipio = delegacionMunicipio;
  }

  public RequestDatosGeneralesPersonaDomicilio ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

   /**
   * Reportar la ciudad a la cual pertenece la dirección contenida en el elemento Dirección.
   * @return ciudad
  **/
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public RequestDatosGeneralesPersonaDomicilio estado(CatalogoEstados estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Get estado
   * @return estado
  **/
  public CatalogoEstados getEstado() {
    return estado;
  }

  public void setEstado(CatalogoEstados estado) {
    this.estado = estado;
  }

  public RequestDatosGeneralesPersonaDomicilio cp(String cp) {
    this.cp = cp;
    return this;
  }

   /**
   * El código postal reportado debeestar compuesto por 5 dígitos. Para que el código postal sea válido deberá corresponder al estado reportado.
   * @return cp
  **/
  public String getCp() {
    return cp;
  }

  public void setCp(String cp) {
    this.cp = cp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDatosGeneralesPersonaDomicilio requestDatosGeneralesPersonaDomicilio = (RequestDatosGeneralesPersonaDomicilio) o;
    return Objects.equals(this.direccion, requestDatosGeneralesPersonaDomicilio.direccion) &&
        Objects.equals(this.colonia, requestDatosGeneralesPersonaDomicilio.colonia) &&
        Objects.equals(this.delegacionMunicipio, requestDatosGeneralesPersonaDomicilio.delegacionMunicipio) &&
        Objects.equals(this.ciudad, requestDatosGeneralesPersonaDomicilio.ciudad) &&
        Objects.equals(this.estado, requestDatosGeneralesPersonaDomicilio.estado) &&
        Objects.equals(this.cp, requestDatosGeneralesPersonaDomicilio.cp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(direccion, colonia, delegacionMunicipio, ciudad, estado, cp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDatosGeneralesPersonaDomicilio {\n");
    
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    colonia: ").append(toIndentedString(colonia)).append("\n");
    sb.append("    delegacionMunicipio: ").append(toIndentedString(delegacionMunicipio)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    cp: ").append(toIndentedString(cp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
