/*
 * Guardian Express
 * <p>Guardian Express, Fraud Score estima la probabilidad de fraude de originación en el momento de otorgamiento del crédito, representada en un puntaje de 0 a 1, donde un valor más alto indica un mayor riesgo de fraude. El formato express da apertura a que pueda ser consumido sin necesidad de un Rerporte de Crédito..<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.GuardianExpressSimulacion.client.model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * RequestDatosGeneralesPersona
 */


public class RequestDatosGeneralesPersona {
  @SerializedName("primerNombre")
  private String primerNombre = null;

  @SerializedName("segundoNombre")
  private Object segundoNombre = null;

  @SerializedName("apellidoPaterno")
  private String apellidoPaterno = null;

  @SerializedName("apellidoMaterno")
  private String apellidoMaterno = null;

  @SerializedName("apellidoAdicional")
  private Object apellidoAdicional = null;

  @SerializedName("fechaNacimiento")
  private String fechaNacimiento = null;

  @SerializedName("RFC")
  private String RFC = null;

  @SerializedName("domicilio")
  private RequestDatosGeneralesPersonaDomicilio domicilio = null;

  public RequestDatosGeneralesPersona primerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
    return this;
  }

   /**
   * Primer nombre de la persona
   * @return primerNombre
  **/
  public String getPrimerNombre() {
    return primerNombre;
  }

  public void setPrimerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
  }

  public RequestDatosGeneralesPersona segundoNombre(Object segundoNombre) {
    this.segundoNombre = segundoNombre;
    return this;
  }

   /**
   * Segundo nombre de la persona, si tiene
   * @return segundoNombre
  **/
  public Object getSegundoNombre() {
    return segundoNombre;
  }

  public void setSegundoNombre(Object segundoNombre) {
    this.segundoNombre = segundoNombre;
  }

  public RequestDatosGeneralesPersona apellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
    return this;
  }

   /**
   * Apellido paterno de la persona
   * @return apellidoPaterno
  **/
  public String getApellidoPaterno() {
    return apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public RequestDatosGeneralesPersona apellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
    return this;
  }

   /**
   * Apellido materno de la persona
   * @return apellidoMaterno
  **/
  public String getApellidoMaterno() {
    return apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public RequestDatosGeneralesPersona apellidoAdicional(Object apellidoAdicional) {
    this.apellidoAdicional = apellidoAdicional;
    return this;
  }

   /**
   * Apellido adicional de la persona, si tuviere
   * @return apellidoAdicional
  **/
  public Object getApellidoAdicional() {
    return apellidoAdicional;
  }

  public void setApellidoAdicional(Object apellidoAdicional) {
    this.apellidoAdicional = apellidoAdicional;
  }

  public RequestDatosGeneralesPersona fechaNacimiento(String fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
    return this;
  }

   /**
   * Fecha de nacimiento de la persona, en el formato especificado (por defecto dd-MM-yyyy)
   * @return fechaNacimiento
  **/
  public String getFechaNacimiento() {
    return fechaNacimiento;
  }

  public void setFechaNacimiento(String fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
  }

  public RequestDatosGeneralesPersona RFC(String RFC) {
    this.RFC = RFC;
    return this;
  }

   /**
   * RFC con homoclave de la persona
   * @return RFC
  **/
  public String getRFC() {
    return RFC;
  }

  public void setRFC(String RFC) {
    this.RFC = RFC;
  }

  public RequestDatosGeneralesPersona domicilio(RequestDatosGeneralesPersonaDomicilio domicilio) {
    this.domicilio = domicilio;
    return this;
  }

   /**
   * Get domicilio
   * @return domicilio
  **/
  public RequestDatosGeneralesPersonaDomicilio getDomicilio() {
    return domicilio;
  }

  public void setDomicilio(RequestDatosGeneralesPersonaDomicilio domicilio) {
    this.domicilio = domicilio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDatosGeneralesPersona requestDatosGeneralesPersona = (RequestDatosGeneralesPersona) o;
    return Objects.equals(this.primerNombre, requestDatosGeneralesPersona.primerNombre) &&
        Objects.equals(this.segundoNombre, requestDatosGeneralesPersona.segundoNombre) &&
        Objects.equals(this.apellidoPaterno, requestDatosGeneralesPersona.apellidoPaterno) &&
        Objects.equals(this.apellidoMaterno, requestDatosGeneralesPersona.apellidoMaterno) &&
        Objects.equals(this.apellidoAdicional, requestDatosGeneralesPersona.apellidoAdicional) &&
        Objects.equals(this.fechaNacimiento, requestDatosGeneralesPersona.fechaNacimiento) &&
        Objects.equals(this.RFC, requestDatosGeneralesPersona.RFC) &&
        Objects.equals(this.domicilio, requestDatosGeneralesPersona.domicilio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primerNombre, segundoNombre, apellidoPaterno, apellidoMaterno, apellidoAdicional, fechaNacimiento, RFC, domicilio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDatosGeneralesPersona {\n");
    
    sb.append("    primerNombre: ").append(toIndentedString(primerNombre)).append("\n");
    sb.append("    segundoNombre: ").append(toIndentedString(segundoNombre)).append("\n");
    sb.append("    apellidoPaterno: ").append(toIndentedString(apellidoPaterno)).append("\n");
    sb.append("    apellidoMaterno: ").append(toIndentedString(apellidoMaterno)).append("\n");
    sb.append("    apellidoAdicional: ").append(toIndentedString(apellidoAdicional)).append("\n");
    sb.append("    fechaNacimiento: ").append(toIndentedString(fechaNacimiento)).append("\n");
    sb.append("    RFC: ").append(toIndentedString(RFC)).append("\n");
    sb.append("    domicilio: ").append(toIndentedString(domicilio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
