/*
 * Guardian Express
 * <p>Guardian Express, Fraud Score estima la probabilidad de fraude de originación en el momento de otorgamiento del crédito, representada en un puntaje de 0 a 1, donde un valor más alto indica un mayor riesgo de fraude. El formato express da apertura a que pueda ser consumido sin necesidad de un Rerporte de Crédito..<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.GuardianExpressSimulacion.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * ResponseGuardianDG
 */

public class ResponseGuardianDG {
  @SerializedName("score")
  private String score = null;

  @SerializedName("razones")
  private List<String> razones = null;

  @SerializedName("folioConsulta")
  private String folioConsulta = null;

  public ResponseGuardianDG score(String score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  public String getScore() {
    return score;
  }

  public void setScore(String score) {
    this.score = score;
  }

  public ResponseGuardianDG razones(List<String> razones) {
    this.razones = razones;
    return this;
  }

  public ResponseGuardianDG addRazonesItem(String razonesItem) {
    if (this.razones == null) {
      this.razones = new ArrayList<String>();
    }
    this.razones.add(razonesItem);
    return this;
  }

   /**
   * Get razones
   * @return razones
  **/
  public List<String> getRazones() {
    return razones;
  }

  public void setRazones(List<String> razones) {
    this.razones = razones;
  }

  public ResponseGuardianDG folioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
    return this;
  }

   /**
   * Get folioConsulta
   * @return folioConsulta
  **/
  public String getFolioConsulta() {
    return folioConsulta;
  }

  public void setFolioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseGuardianDG responseGuardianDG = (ResponseGuardianDG) o;
    return Objects.equals(this.score, responseGuardianDG.score) &&
        Objects.equals(this.razones, responseGuardianDG.razones) &&
        Objects.equals(this.folioConsulta, responseGuardianDG.folioConsulta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, razones, folioConsulta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseGuardianDG {\n");
    
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    razones: ").append(toIndentedString(razones)).append("\n");
    sb.append("    folioConsulta: ").append(toIndentedString(folioConsulta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
